name: Scrape Sakanction News

on:
  schedule:
    - cron: '0 7 * * *'   # 毎日 7:00 UTC に実行（日本時間では+9時間 → 16:00 JST）。必要なら調整
  workflow_dispatch:      # 手動トリガー可能

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scrape_news.py
          git status
          git add data/news.json || true
          # commit only if changes exist
          if ! git diff --quiet --exit-code; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "Update news.json"
            git push
          else
            echo "No changes to commit"
          fi
